version: '3.8'
services:
  backend:
    build:
      context: ./backend
    environment:
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SALT_ROUNDS=${SALT_ROUNDS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  pgdata:
networks:
  backend:

